### ISSUE TITLE
Variable "forms" does not exist.

### ISSUE THREAD

**Issue by GMConsultant** [bitboxde/minifier#5]
click on settings plugins...

/craft/vendor/bitboxde/minifier/src/templates/_includes/forms.html
line 18: ` {% set formsMacros = source(forms) %}`

And crash...

**Comment by lukeholder** [comment]
Confirm this is the case.

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/133571/63155958-4044b880-c046-11e9-8d50-756ba1852883.png">

**Comment by bitboxfw** [comment]
Fixed with version 2.0.2

**Comment by lukeholder** [comment]
@bitboxfw issue still persists in 2.0.2

Had to change line #17 to 

```
{% if forms.autosuggest is defined or forms is defined %}
```

**Comment by bitboxfw** [comment]
Interesting.. which version of Craft did you use? We have tested it on 3 different environments with Craft 3.2 without any problems.

**Comment by bitboxfw** [comment]
@lukeholder Found the problem with Craft 3.1 ([#6](https://github.com/bitboxde/minifier/issues/6)). I changed line 17 to your suggestion. Could you please check if everything is working fine now for you?

**Comment by lukeholder** [comment]
Yes it works, but I don't get the autosuggest fields (as `forms` is always false). My fix was just a quick one to get the page working. The loading of the `forms` variable is the issue.

**Comment by lukeholder** [comment]
Also should be `{% if forms.autosuggest is defined and forms is defined %}` with an `and` as the or is the wrong logic.

**Comment by bitboxfw** [comment]
Allright, have to take a deeper look within the next days. But thanks so far!
